// Generated by CoffeeScript 1.7.1
(function() {
  var INTERVAL, fs, logFile, mailOptions, main, nodemailer, now, smtpTransport, title;

  nodemailer = require("nodemailer");

  fs = require("fs");

  INTERVAL = 60 * 60 * 1000;

  smtpTransport = nodemailer.createTransport("SMTP", {
    service: "Gmail",
    auth: {
      user: "iwark02@gmail.com",
      pass: "kouhei7y"
    }
  });

  now = new Date();

  title = "log(" + now.toLocaleString() + ")";

  logFile = fs.readFileSync('./twlog', 'utf-8');

  mailOptions = {
    from: "twclient <iwark02@gmail.com>",
    to: "iwark02@gmail.com",
    subject: title,
    text: logFile.toString()
  };

  main = function() {
    return smtpTransport.sendMail(mailOptions, function(error, response) {
      if (error) {
        return console.log(error);
      } else {
        console.log("Message sent: " + response.message);
        return fs.writeFileSync('./twlog', '');
      }
    });
  };

  main();

  setInterval(main, INTERVAL);

}).call(this);
