- screen_name: maamin4
  consumer_key:        Afhyk2nTSaJvfiwXp0pd50E6C
  consumer_secret:     Dy7r1UQML24Xsy7vhsO9Eu5fj3y6qnMPQNAPQHYjVe3BjaxkvS
  access_token:        2368012110-KiAn5hkBZrQGYE587kQxL6DRLtybHN0jPUtHHdK
  access_token_secret: x1hBZc7nEnIi4y5Uta6LLWumYdPYL0ESlZbh3OnCGbXmi

- screen_name: sayakarzmrumgx
  consumer_key:        y9MH162TvhljOcLdlG9m4mkbc
  consumer_secret:     epMyUD0bdPXTnB8YsCEvM287BVr26rrMIDHYMHIMWtMFM3fSIZ
  access_token:        2454429072-z4ieC1hnsjd5JVm5ss2X9Ly8YwJV5Y2BnGYRckD
  access_token_secret: eiQI8iSkWb2i5Ds2htyQWVJx2Ostw37eb3gq8wWfUfrdD

- screen_name: maa_xoxoxo
  consumer_key:        7jvwTqMCx5AOvcXLPYA6nIOH7
  consumer_secret:     N4FaYCcEqVkNbttpRpTvhBaPUUz3LANhIPdy2VoorXtn2qsOCf
  access_token:        2400128545-ICbA8GBxXaBJZdEUjd0CxMMFUTBokO924g7d7wf
  access_token_secret: 6tVDuJO7cl57ZEpZoiD5M2T6btnITDmK1oYkj9QSN82Mo