- step: 1 # followed
  message: フォローありがとうございます♡なかよくして下さい♪どこ住みですかぁ〜(*´꒳`*)？？

- step: 3 # dm1_replyed
  message: そうなんだ︎うちは大阪だよー♪  いまいくつなのー？（≧∇≦）

- step: 5 # dm2_replyed
  message: うちは21だよ♪︎ 去年学校卒業して大阪に引っ越してきたんだ(〃▽〃)ﾎﾟｯ

- step: 7 # dm3_replyed
  message: こっちに友達いなさすぎてちょー寂しいんだよね>_<  よかったらLINEしよーよ(´∀｀艸)  http://line.naver.jp/ti/p/D1

- step: 9 # dm4_replyed
  message: てか、LINEしよーよ*\(^o^)/* http://line.naver.jp/ti/p/ThI-12pukm これ押したら追加できるやつだからさ（≧∇≦）