followed     : 1   # フレンドからのフォローを検知した段階
dm1_sent     : 2   # １段階目のDMを送信した状態
dm1_replyed  : 3   # DMに対する１度目の返信を検知した段階
dm2_sent     : 4   # ２段階目のDMを送信した状態
dm2_replyed  : 5   # DMに対する２度目の返信を検知した段階
dm3_sent     : 6   # ３段階目のDMを送信した状態
dm3_replyed  : 7   # DMに対する３度目の返信を検知した段階
dm4_sent     : 8   # ４段階目のDMを送信した状態
dm4_replyed  : 9   # DMに対する４度目の返信を検知した段階
dm5_sent     : 10  # ５段階目のDMを送信した状態
finished     : 99  # 最初からフレンド状態